feat: feature review activity
OmarMWarraich/todo-list-review pull request #1
Opened 2022-08-23 12:40 UTC by OmarMWarraich

### In this PR, I have completed the following tasks:

- [ ] Set up a new project with webpack.
- [ ] Create index.html using the HTML Webpack Plugin.
- [ ] Set an array of objects(simple to do tasks) in index.js.
- [ ] Write a function to iterate over the tasks array and populate the HTML element.
- [ ] On page load, render the dynamically created tasks.
- [ ] Load CSS by Webpack Syle/CSS Loader.
- [ ] Remove all hard coded items from the tasks array.
- [ ] Create a new JS file for the new functionality.
- [ ] Implement functions for adding, deleting and editing a new task.
- [ ] Update all the remaining indexes after the deletion of a task.
- [ ] Save all changes in the local storage.
- [ ] Add a new JS file in a module containing methods related to status updates.
- [ ] Add event listener to the checkbox.
- [ ] Update items object's value for completed key upon user actions.
- [ ] Implement "Clear all completed" button through a function .
- [ ] Update the correct list of values on page reload.

2022-08-25 05:09 UTC, tahseenzahra requested changes
## Hi @OmarMWarraich

Good job so far! I know you have worked hard on making this milestone. But there are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
## Required Changes ♻️

- [ ] Kindly check the comments under the review.

2022-08-25 05:09 UTC, tahseenzahra commented on src/modules/Tasks.js
> +  };
I think :thinking: it would be better to have the functionality of the "enter" button along with clicking on the icon for entering the data in the list as it was in the task shown here is the link for that 
[https://www.youtube.com/watch?v=AcUd-_Yjjqg&ab_channel=EmiliaAndrzejewska](url)

2022-08-25 05:09 UTC, tahseenzahra commented on src/modules/Tasks.js
> +      });
Kindly add the delete icon for the particular list item when it's selected as given in the style.
![issue0](https://user-images.githubusercontent.com/54817285/186576669-f6483660-091b-4e14-b792-9d6669236ed2.png)
and here is your style 
![issue0](https://user-images.githubusercontent.com/54817285/186576775-038fa08b-09ca-46d3-b64e-98075560fdba.png)

2022-08-25 05:09 UTC, tahseenzahra commented on src/modules/TaskStatus.js
> +}
Please have the line through text for the task marked as completed :ballot_box_with_check: .

2022-08-25 05:09 UTC, tahseenzahra commented on src/modules/Tasks.js
> +                            <div class="dots"></div>
:point_right: Please add the hover effect on all icons as shown in the given style 
![issue0](https://user-images.githubusercontent.com/54817285/186579036-4d89fed6-6438-4c49-8905-e4eae1f608c2.png)

2022-08-31 09:08 UTC, normainobary2021 approved these changes
Hi @OmarMWarraich,  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-31 15:24 UTC, merged